algo = input('Digite algo: ')
print(f'O tipo primitivo desse valor é{type(algo)}')
print(f'Só tem espaços?', algo.isspace())
print(f'É um número?', algo.isnumeric())
print(f'É alfábetico?', algo.isalpha())
print(f'É alfanúmerico?', algo.isalnum)
print(f'Está em maiscula?', algo.isupper())
print(f'Está em minuscula?', algo.islower())
print(f"Está capitalizado", algo.istitle())

